################################################################################
# configuration
################################################################################
[hugoVersion]
extended = false
min = "0.84.4"

[[mounts]]
source = "config"
target = "config"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "layouts"
target = "layouts"
